version: "3.9"

services:
  fuel-explorer-pgsql:
    platform: linux/amd64
    container_name: fuel-explorer-pgsql
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - fuel-explorer-db:/usr/local/postgres
    environment:
      - POSTGRES_PASSWORD=postgres
      - PGUSER=postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-U", "postgres", "-d", "postgres"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s

  fuel-explorer-core:
    platform: linux/amd64
    container_name: fuel-explorer-core
    environment:
      MIN_GAS_PRICE: ${GAS_PRICE}
      # This is the private key of the consensus.PoA.signing_key in the chainConfig.json
      # this key is responsible for validating the transactions
      CONSENSUS_KEY: ${WALLET_SECRET}
    build: ./fuel-core
    ports:
      - "4000:4000"
    volumes:
      - fuel-explorer-core-db:/mnt/db
    healthcheck:
      test: curl --fail http://localhost:4000/health || exit 1
      interval: 1s
      timeout: 5s
      retries: 20

  fuel-explorer-indexer:
    platform: linux/amd64
    container_name: fuel-explorer-indexer
    image: ghcr.io/fuellabs/fuel-indexer:latest
    command: sh /usr/local/scripts/run-indexer.sh
    ports:
      - "29987:29987"
    volumes:
      - ./fuel-indexer/scripts:/usr/local/scripts
      - fuel-explorer-indexer-db:/usr/local/fuel-indexer
    depends_on:
      - fuel-explorer-pgsql
      - fuel-explorer-core
    links:
      - fuel-explorer-pgsql
      - fuel-explorer-core

volumes:
  fuel-explorer-db:
  fuel-explorer-indexer-db:
  fuel-explorer-core-db:
