[package]
name = "indexer"
version = "0.0.0"
edition = "2021"
publish = false

[lib]
crate-type = ['cdylib']

[dependencies]
fuel-indexer-macros = { version = "0.8", default-features = false }
fuel-indexer-plugin = { version = "0.8" }
fuel-indexer-schema = { version = "0.8", default-features = false }
fuel-tx = "0.26"
fuels-core = { version = "0.38.1", default-features = false }
fuels-macros = { version = "0.38.1" }
fuels-types ={ version = "0.38.1", default-features = false }
getrandom = { version = "0.2", features = ["js"] }
serde = { version = "1.0", default-features = false, features = ["derive"] }
serde_json = "1.0.96"